package(default_visibility = ["//visibility:public"])

cc_test(
    name = "debug_test",
    srcs = ["debug_test.cpp"],
    deps = [
            "@gtest//:gtest",
            "@gtest//:gtest_main",
            "//Fulfil.LFR.RoverFw/tools:tools",
    ],
)

cc_test(
    name = "csv_parse_test",
    srcs = [
            "csv_parse_test.cpp"],
    deps = [
            "//Fulfil.LFR.RoverFw/tools:tools",
            "@gtest//:gtest",
            "@gtest//:gtest_main",
    ],
)
