package(default_visibility = ["//visibility:public"])

cc_library(
    name = "tools",
    srcs = [
            "debug.cpp",
            "timer.cpp",
            "common_helpers.cpp",
    ],
    hdrs = [
            "debug.h",
            "timer.h",
            "descriptor.h",
            "common_helpers.h",
            "FIFO.h"
            ],
)